### ISSUE TITLE
Please test fork for OS platform additions

### ISSUE THREAD

**Issue by patgmac** [tburgin/AbsoluteManageExport#16]
I have some proposed additions I'd like some help with testing before I do a PR. This fork adds the ability to add additional criteria to a LANrev SD package, including: os_platform min_os max_os platform_arch. 

See the README for some additional details. 

https://github.com/patgmac/AbsoluteManageExport

**Comment by jbaker10** [comment]
I will try to test this tomorrow and let you know what I find!

**Comment by patgmac** [comment]
Thank you. Hopefully adding 1 criteria doesn't require any/all the others. I think I have the bases covered but after a while, my head started hurting. ;-)

**Comment by jbaker10** [comment]
@patgmac I have tested the following successfully:
* Running the recipe without any of the new conditions
* Only using one at a time:
  * `max_os`
  * `min_os`
  * `os_platform`
  * `platform_arch`
* Using all 4 in the same recipe
* Using only `max_os` and `min_os`
* Lots of variations in between haha

I have a suggestion for the `platform_arch`. It seems that if this is only used for Windows, it should automatically change the `OS_platform` to be Windows (`4`), or have a condition that checks and fails gracefully if the user uses `platform_arch` without _also_ using `os_platform`.

There are a lot of different pieces here that somewhat rely on each other in order to work properly, so while I think some of this can be put on the user to ensure they have it set properly, the setting of the `os_platform` automatically when using `platform_arch` I think would be fairly easy and one that I think makes sense to automate.

**Comment by patgmac** [comment]
Good call. Yea, if os_platform is Win, platform_arch needs to be set to one of the Win arch's. platform_arch CAN be used for Mac, but I can't imagine anyone needing to specify PPC/Intel anymore.

**Comment by jbaker10** [comment]
Well kind of the opposite, since in the notes for the input variable you state:
```
'platform_arch': {
            'description': 'Specify the Windows platform architecture. Choices are: x86, x64, or any. Do not specify for Mac packages',
            'required': False,
```
It implies you shouldn't use it for Mac packages.
So I think you just make it a conditional that says:
```
if platform_arch is not None:
    os_platform = 4
```
