### ISSUE TITLE
Question about LANRev

### ISSUE THREAD

**Issue by eahrold** [tburgin/AbsoluteManageExport#2]
@tburgin, 

I'm not too familiar with AbsoluteManage, but we are trying to integrate it into [AutoPkgr](https://github.com/lindegroup/autopkgr). I just was wondering if you would speak to the reason LANrev Admin.app needs to be open when using AbsoluteManageExport.py? Is LANRev mounting a share? Can you only access the DB when it's open? Things of that nature.

Thanks for your time.

**Comment by tburgin** [comment]
@eahrold The `LANrev Admin.app` needs to be open because of the ugly way the Absolute engineers implemented the `importsoftwarepackage` feature. They don't give us a nice API like casper or munki. They use some type of listener for `lanrevadmin://` requests. They basically automated the import and commit features of `LANrev Admin.app`. It needs to be open to actually talk back to your Absolute Manage server.

That said, you don't have to have `LANrev Admin.app` open at runtime of this processor. IF you have your admin username and password for Absolute Manage cached in the keychain, the `LANrev Admin.app` will auto launch when called from AutoPKG.

**Comment by tburgin** [comment]
LANrev does not mount a share. It compress up the payload and software package plist into a proprietary file type, then sends it to the main Absolute Manage server over port 3972 (default). This is all handled through the `LANrev Admin.app`.

The local sqlite3 database is actually always available, but it is only updated when the `LANrev Admin.app` is open. This is the database we use to check if the payload already exists.

**Comment by eahrold** [comment]
Have you ever tested to see what would happen if `LANRev Admin.app` were unable to launch, such as if the login window when autopkg was invoked?

**Comment by tburgin** [comment]
Does not launch. Fails to query or import any packages...

**Comment by tburgin** [comment]
@RIMorton Want to submit a feature request? Upload of software packages without `LANRev Admin.app` having to be open? I can fill in the rest.

**Comment by RIMorton** [comment]
That one might be tough, but I will file it. Basically the URL handler is how we cheat the system so to speak.I believe the URL handler will always launch an application though (I could be very wrong here). Basically, I believe someone has to be logged in to do this.

I was thinking the same thing where we would run the script on the server directly, but most of our users run the AM Server on a Windows system anyway, so that does not help.

COBRA-21775 has been created for you.

**Comment by homebysix** [comment]
Hi @tburgin, nice to meet you at PSU last week! Pam showed me the contents of her /Applications folder, and it looks like her version of the app is called `Absolute Manage Admin.app` instead of `LANRev Admin.app`. Is that a recent change?

It's related to @eahrold's questions above, and [this](https://github.com/lindegroup/autopkgr/issues/217). Thanks!

**Comment by RIMorton** [comment]
Well, it should show as Absolute Manage Admin.app, but that is where it will then get a little odd and I am not sure how it is done to be honest. In Finder, it should show as Absolute Manage Admin.app but in Terminal it would appear as LANrev Admin.app (using ls -al /Applications). In order for the integration to work, you need to be at version 6.5 or greater of Absolute Manage. Having it called Absolute Manage Admin happened more than 4 years ago as I had not started working for Absolute when they change occurred.

**Comment by eahrold** [comment]
@RIMorton, that's wild. Finder must be pulling the name from the Info.plist or something to that extent. 

Thanks for the 6.5 tip, we'll make sure to get that included in the prerequisite check.

**Comment by tburgin** [comment]
@eahrold @RIMorton That is wild. This explains why I was so convinced that `/Applications/LANrev Admin.app/` was the path. Pam proved me wrong by looking at the Finder...

**Comment by seansgm** [comment]
Pretty sure it's been like this since I started using it a couple of years
ago.  It's set in the metadata:

mdls -name kMDItemDisplayName /Applications/Absolute/LANrev\ Admin.app

kMDItemDisplayName = "Absolute Manage Admin"


Same as Illustrator:


mdls -name kMDItemDisplayName /Applications/Adobe\ Illustrator\
CS5.1/Adobe\ Illustrator.app

kMDItemDisplayName = "Adobe Illustrator CS5.1"

**Comment by RIMorton** [comment]
Very cool. Thanks for the detailed explanation. I must say, not a big fan of this, but it does work and made it easy to update from LANrev Admin.app to Absolute Manage Admin.app

**Comment by eahrold** [comment]
@RIMorton, @seansgm I was wondering if either of you would confirm that the 6.5 version number is set as the CFBundleShortVersionString key in the info.plist.  Thanks.

**Comment by seansgm** [comment]
Appears to be:

defaults read /Applications/Absolute/LANrev\ Admin.app/Contents/Info.plist
| grep -i version

    CFBundleInfoDictionaryVersion = "6.0";

    CFBundleShortVersionString = "6.7";

    CFBundleVersion = 3755;

    DTPlatformVersion = GM;

    LSMinimumSystemVersion = "10.6.0";

**Comment by eahrold** [comment]
@tburgin, 
I wanted to check with you and see if you had a preference for a short name for AbsoluteManageExport so we can fit it on a UI button. 

I just realized we have it as AMExporter, but it should be AMExport. 
Do you have a preference for either of these, or another suggestion ( less than 16 chars )?

Thanks.

**Comment by tburgin** [comment]
AMExport sounds good to me.

**Comment by tburgin** [comment]
The name is kind of confusing...

Historically Absolute Manage didn't have an interface for importing sd packages. So I named it `AbsoluteManageExport`, because it exported from AutoPkg.

Enter AM 6.5. They gave us a tiny little sliver of a feature. We were able to upload sd packages, clunky, but at least it works.

We had recipes and the such all using this name, so I never changed it...

**Comment by RIMorton** [comment]
Yeah, I could see where calling it somethingImporter makes sense. AMImporter or ManageImporter would make sense if you wanted to shorten it a little. Right now, the AM recipes are limited and could be updated pretty easily I think.

**Comment by homebysix** [comment]
+1 for AMImporter, AbsoluteImporter, or something like that. Would match nicely with JSSImporter, MacPatchImporter, and MunkiImporter.

**Comment by tburgin** [comment]
I like `AbsoluteImporter`
Should have some time next week to look into changing this

**Comment by patgmac** [comment]
You may want to wait until after this Absolute/LANrev shakeup settles down before renaming anything. Who knows what AM will be called.

**Comment by patgmac** [comment]
LANrevImporter?

**Comment by jbaker10** [comment]
At this point, I have 2 concerns:
* Will with 7.0 being under HEAT, any of this change _again_?
* With more and more folks using this in recipe's, is it worth breaking all of those?

Unless people feel the need to change the identifier, I'd almost suggest leaving it untouched as most people know what it's for. This might be once again something we revisit if HEAT changes any of the naming convention down deep in the agent, but otherwise I almost think to leave it alone is easiest, but open for discussion!

**Comment by patgmac** [comment]
I personally think it should be changed sooner, rather than later. Currently, theres only about 3 of us that have made recipes for AM/LANrev, so it wouldn't be too hard to get those changed. At some point, HEAT is going to sign on new customers that may have never heard of Absolute Manage. 

Plus, at it's core, it's always been called LANrev. The original creator (Martin) made it a point to keep the LANrev name in there all along, even though the Absolute marketing people made him change it to Absolute Manage.

**Comment by tburgin** [comment]
Mr. Baker has been actively maintaining this for NIH, I will defer to his wishes for the name :smile:

**Comment by jbaker10** [comment]
We have officially renamed this processor to `LANrevImporter` and it is now housed at https://github.com/jbaker10/LANrevImporter
